- name: Add key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: Add CRAN repo
  apt_repository:
    repo: "deb https://cran.rstudio.com/bin/linux/ubuntu/ bionic-cran35/"
    mode: 644

- name: Install R
  apt:
    name:
      - r-base
      - r-base-dev
    state: latest
    autoclean: yes
    update_cache: true
