---
- name: Add CRAN repo
  ansible.builtin.deb822_repository:
    name: cran
    types: deb
    suites: "noble-cran40/"
    uris: https://cloud.r-project.org/bin/linux/ubuntu
    architectures: amd64
    signed_by: https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc
    state: present

- name: Install R
  ansible.builtin.apt:
    name:
      - r-base
      - r-base-dev
    state: present
    autoclean: true
    update_cache: true
