- name: Add key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: Add CRAN repo
  ansible.builtin.apt_repository:
    repo: "deb https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/"
    mode: 644

- name: Install R
  ansible.builtin.apt:
    name:
      - r-base
      - r-base-dev
    state: present
    autoclean: true
    update_cache: true
