- name: Laptop
  hosts: 127.0.0.1
  become: true
  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache=yes
        upgrade=dist # to resolve the warning message "Could not find aptitude. Using apt-get instead"
      changed_when: false

  tasks:
    - name: Ubuntu package install upgrade
      ansible.builtin.include_tasks: tasks/packages.yml
      tags: finished

    - name: Install R
      ansible.builtin.include_tasks: tasks/installR.yml
      tags: finished

    - name: Install RStudio
      ansible.builtin.include_tasks: tasks/installRstudio.yml
      tags: finished

    - name: Install slack
      ansible.builtin.include_tasks: tasks/installSlack.yml
      tags: finished

    - name: Install chrome
      ansible.builtin.include_tasks: tasks/installChrome.yml
      tags: finished

    - name: Install r dependencies
      ansible.builtin.include_tasks: tasks/installRdependencies.yml
      tags: finished

    - name: Install Google Earth
      ansible.builtin.include_tasks: tasks/installGoogleEarth.yml
      tags: finished

    - name: Install QGIS
      ansible.builtin.include_tasks: tasks/installQGIS.yml
      tags: finished
