- name: Setting up a local laptop
  hosts: linux
  connection: local
  #debugger: on_skipped
  debugger: on_failed
  roles:
    - role: gantsign.atom-packages
      users:
        - username: "{{ansible_facts['user_id']}}"
          atom_packages:
            - atom-terminal
            - linter
            - linter-eslint
            - linter-jsonlint
            - intentions
            - busy-signal
            - linter-ui-default
            - platformio-ide-terminal
      when: ansible_facts['os_family'] == 'Debian'
  tasks:
    - name: Zotero
      include: roles/uncommon/tasks/zotero.yml
  # Should docker be done here
  # Anaconda should be per user
  # pyenv should be per user
