# from Ansible Galaxy
- src: gantsign.atom-packages
  version: 1.2.0
- src: markosamuli.pyenv
  version: v2.1.1
- src: stephdewit.nvm
  version: v3.2.0
- src: ocha.yarn
  version: v1.2.0
- src: gantsign.visual-studio-code
- src: stefangweichinger.ansible_rclone
