# from Ansible Galaxy
collections:
  - name: community.general

roles:
  - src: gantsign.visual-studio-code

#- src: stephdewit.nvm
#  version: v3.2.0
#- src: ocha.yarn
#  version: v1.2.0
#- src: stefangweichinger.ansible_rclone
