- name: Setting up a local laptop
  hosts: linux
  connection: local
  become: yes
  roles:
    - role: common
      when: ansible_facts['os_family'] == 'Debian'
    - role: gantsign.atom-packages
      user:
        - username: ansible_facts['user_id']
          atom_packages:
            - atom-terminal
            - linter
            - linter-eslint
            - linter-jsonlint
            - platformio-ide-terminal
    - role: uncommon
      when: ansible_facts['os_family'] == 'Debian'
    - role: geospatial
      when: ansible_facts['os_family'] == 'Debian'
