- name: Setting up a local laptop
  hosts: linux
  connection: local
  become: yes
  roles:
    - role: common
      when: ansible_facts['os_family'] == 'Debian'
    - role: uncommon
      when: ansible_facts['os_family'] == 'Debian'
