- name: Setting up a local laptop
  hosts: linux
  connection: local
  become: yes
  #debugger: on_skipped
  debugger: on_failed
  roles:
    - role: common
      when: ansible_facts['os_family'] == 'Debian'
    # Atom Packages, If you want to install for many users list them by name.
    # Otherwise use the per_user.yml do configure just for the user who runs it.
    # - role: gantsign.atom-packages
    #   users:
    #     - username: "{{ansible_facts['user_id']}}"
    #       atom_packages:
    #         - atom-terminal
    #         - linter
    #         - linter-eslint
    #         - linter-jsonlint
    #         - intentions
    #         - busy-signal
    #         - linter-ui-default
    #         - platformio-ide-terminal
    #   when: ansible_facts['os_family'] == 'Debian'
    - role: uncommon
      when: ansible_facts['os_family'] == 'Debian'
    - role: graphics
      when: ansible_facts['os_family'] == 'Debian'
    - role: geospatial
      when: ansible_facts['os_family'] == 'Debian'
    - role: r
      when: ansible_facts['os_family'] == 'Debian'
    - role: ocha.yarn
