- name: Install Gdebi
  apt: 
        name: gdebi

- name: Get the archive of RStudio Desktop
  get_url: url=https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb dest=/tmp/rstudio.deb
  become: no

- name: Install RStudio Desktop
  command: /usr/bin/gdebi --non-interactive /tmp/rstudio.deb
