- name: Install Gdebi
  apt:
        name: gdebi

- name: Get the archive of Google Earth
  get_url:
    url: https://dl.google.com/dl/earth/client/current/google-earth-pro-stable_current_amd64.deb
    dest: /tmp/google-earth-pro-stable_current_amd64.deb
  become: no

- name: Install Google Earth
  command: /usr/bin/gdebi --non-interactive /tmp/google-earth-pro-stable_current_amd64.deb
