# Remote Desktop client for connecting to Windows machines
# https://remmina.org/how-to-install-remmina/
- name: Add Remmina Repo
  apt_repository:
    repo: 'ppa:remmina-ppa-team/remmina-next'
    state: present
    update_cache: yes

- name: Install Remmina packages
  apt:
    pkg:
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-secret
      - remmina-plugin-spice
    state: latest
    update_cache: yes
