# This is awscli v1
#- name: Install AWS cli tools
#  pip:
#    name: awscli
#    executable: pip3
#    extra_args: --upgrade --user

# AWS v2
- name: Download AWS cli v2
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscliv2.zip
  register: aws_download_cli
  until: aws_download_cli is succeeded
  retries: 3

#TODO: verify the gpg signing https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install

- name: Extract AWS cli v2 installer
  unarchive:
    dest: /tmp/
    src: /tmp/awscliv2.zip
    owner: "{{ansible_facts['user_id']}}"
    group: "{{ansible_facts['user_id']}}"
    creates: /tmp/aws

- name: Install AWS cli tools v2
  command: "bash /tmp/aws/install --bin-dir /home/{{ansible_facts['user_id']}}/.local/bin/ --install-dir /home/{{ansible_facts['user_id']}}/aws-cli"
  args:
    creates: "/home/{{ansible_facts['user_id']}}/.local/bin/aws"

# Add the ability to update

# Bug, https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1588562
# Make sure .profile exists
# Add this line to ensure autocompletion
# export PATH="$(systemd-path user-binaries):$PATH"

# End user needs to run aws configure after
