# install pixi

- name: Download Pixi
  ansible.builtin.get_url:
    url: "https://pixi.sh/install.sh"
    dest: "/tmp/pixi_install.sh"
    mode: '0744'
  register: python_pixi_download
  until: python_pixi_download is succeeded
  retries: 3

- name: Install pixi
  ansible.builtin.command: "bash /tmp/pixi_install.sh"
  args:
    creates: "/home/{{ ansible_facts['user_id'] }}/.pixi"
  when: python_pixi_download.status_code == 200

# eval "$(pixi completion --shell bash)"
