# TODO find the latest download version https://stackoverflow.com/questions/54645470/download-latest-version-of-slack-automatically
# TODO switch to ansible galaxy? https://github.com/Oefenweb/ansible-slack or snap
# Only needs to be done once, since Slack is then managed by apt

- name: Check if Slack apt source file exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/slack.list
  register: slack_apt_list

# https://slack.com/downloads/linux
- name: Install Slack Desktop
  ansible.builtin.apt:
    deb: https://downloads.slack-edge.com/desktop-releases/linux/x64/4.47.69/slack-desktop-4.47.69-amd64.deb
  when: not slack_apt_list.stat.exists
