---
- name: Geospatial packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: QGIS task
  ansible.builtin.include_tasks:
    file: qgis.yml

- name: Google Earth task
  ansible.builtin.include_tasks:
    file: googleearth.yml
