- name: Install geospatial packages common to all hosts
  ansible.builtin.apt:
    name:
      - gdal-bin
      - libgdal-dev
      - proj-bin
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
      - build-essential
      # - spatialite-bin
      - libtiff-tools
    state: present
    autoclean: true
