---
- name: Add QGIS repo
  ansible.builtin.deb822_repository:
    name: qgis
    types: [deb, deb-src]
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    uris: https://qgis.org/ubuntugis
    architectures: amd64
    signed_by: https://download.qgis.org/downloads/qgis-archive-keyring.gpg
    state: present
    enabled: true


- name: Get repository key fingerprint
  ansible.builtin.uri:
    url: https://api.launchpad.net/devel/~ubuntugis/+archive/ubuntu/ubuntugis-unstable
    return_content: true
    method: GET
    headers:
      Accept: 'application/json'
  register: geospatial_ubuntugis_key

- name: Add Ubuntugis src repo
  ansible.builtin.deb822_repository:
    name: Ubuntugis
    types: deb
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    uris: https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu
    architectures: amd64
    signed_by: |
      {{ lookup('ansible.builtin.url',
      ['https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x',geospatial_ubuntugis_key.json.signing_key_fingerprint]|join ,
      split_lines=False) }}
    state: present

- name: Install QGIS and related packages
  ansible.builtin.apt:
    pkg:
      - qgis
      - python-qgis
      # - qgis-plugin-grass
    state: present
    update_cache: true

# https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu
# https://gis.stackexchange.com/questions/276539/installing-qgis3-on-ubuntu-16-04-xenial-dependency-problem
