---
- name: Add QGIS repo
  ansible.builtin.deb822_repository:
    name: qgis
    types: [deb, deb-src]
    suites: "{{ ansible_distribution_release }}"
    components: main
    uris: https://qgis.org/ubuntugis
    architectures: amd64
    signed_by: https://download.qgis.org/downloads/qgis-archive-keyring.gpg
    state: present
    enabled: true

- name: Add Ubuntugis src repo
  ansible.builtin.apt_repository:
    repo: "ppa:ubuntugis/ubuntugis-unstable"
    state: present
    update_cache: true

- name: Install QGIS and related packages
  ansible.builtin.apt:
    pkg:
      - qgis
      - python-qgis
      # - qgis-plugin-grass
    state: present
    update_cache: true

# https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu
# https://gis.stackexchange.com/questions/276539/installing-qgis3-on-ubuntu-16-04-xenial-dependency-problem
