---
- name: Add Handbrake Repo
  ansible.builtin.apt_repository:
    repo: "ppa:stebbins/handbrake-releases"
    state: present
    update_cache: true

- name: Install Handbrake packages
  ansible.builtin.apt:
    pkg:
      - handbrake-gtk
      - handbrake-cli
    state: present
    update_cache: true
