---
- name: Add Google Chrome repository
  ansible.builtin.deb822_repository:
    name: google
    types: deb
    architectures: amd64
    uris: http://dl.google.com/linux/chrome/deb/
    suites: stable
    components: main
    signed_by: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
    enabled: true

- name: Install Google Chrome
  ansible.builtin.apt:
    name:
      - google-chrome-stable
    state: present
    autoclean: true
    update_cache: true
