---
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Install apt key
  ansible.builtin.apt_key:
    url: "https://packagecloud.io/AtomEditor/atom/gpgkey"
    state: present

- name: Install atom repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    filename: atom
    state: present

- name: Install atom
  ansible.builtin.apt:
    name: atom
    state: present
    update_cache: true
