---
- ansible.builtin.include_tasks: packages.yml
- ansible.builtin.include_tasks: chrome.yml
- ansible.builtin.include_tasks: remmina.yml
- ansible.builtin.include_tasks: slack.yml
- ansible.builtin.include_tasks: ufw.yml
