---
# Remote Desktop client for connecting to Windows machines
# https://remmina.org/how-to-install-remmina/
- name: Add Remmina Repo
  ansible.builtin.apt_repository:
    repo: "ppa:remmina-ppa-team/remmina-next"
    state: present
    update_cache: true

- name: Install Remmina packages
  ansible.builtin.apt:
    pkg:
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-secret
      - remmina-plugin-spice
    state: present
    update_cache: true
