#TODO find the latest download version https://stackoverflow.com/questions/54645470/download-latest-version-of-slack-automatically
- name: "Install Slack Desktop"
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.2.0-amd64.deb
