---
- name: Add SQliteBrowser Repo
  ansible.builtin.apt_repository:
    repo: "ppa:linuxgndu/sqlitebrowser"
    state: present
    update_cache: true

- name: Install SQliteBrowser packages
  ansible.builtin.apt:
    pkg:
      - sqlitebrowser
    state: present
    update_cache: true
