---
- name: Install Firewall (UFW)
  ansible.builtin.apt:
    name:
      - ufw
      - gufw
    state: present
    autoclean: true

# Default is Deny all Incoming, Allow outgoing
- name: Configure UFW Outgoing
  community.general.ufw:
    state: enabled
    policy: allow
    direction: outgoing

- name: Configure UFW Incoming
  community.general.ufw:
    policy: deny
    direction: incoming

# Enable if you want ssh in to work, also need to install openssh server
# - name: Configure UFW SSH Access
#   ufw:
#     rule: limit
#     name: OpenSSH
#     direction: in
