# Install docker packages common to all hosts
# Configre the repo
- name: Add Docker key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    filename: docker
    state: present

# install packages
- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

# Allow non root-user
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ dock_user }}"
    groups: docker
    append: yes

# configure where the docker images are stored
- name: Create docker data directory
  file:
    path: "/home/{{ dock_user}}/.dockerdata"
    state: directory
    owner: "{{ dock_user }}"
    group: docker
    mode: '0755'

- name: install docker configuration file from template
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  become: yes
