- name: Install docker packages common to all hosts
# Configre the repo
- name: Add Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable'
    state: present
    update_cache: yes

# install packages
- name: Install QGIS and related packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

# Allow non root-user
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: {{ansible_facts['user_id']}}
    groups: docker
    append: yes

# configure where the docker images are stored
- name: Create docker data directory
  file:
    path: /home/{{ansible_facts['user_id']}}/.dockerdata
    state: directory
    mode: '0755'
