# Install docker packages common to all hosts
# Configre the repo
- name: Docker
  block:
  - name: Add Docker key
    become: yes
    ansible.builtin.apt_key:
      keyring: /etc/apt/trusted.gpg.d/docker.asc
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repo
    become: yes
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
      filename: docker
      state: present

# install packages
- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
    update_cache: yes

# Allow non root-user
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ dock_user }}"
    groups: docker
    append: yes

# configure where the docker images are stored
- name: Create docker data directory
  file:
    path: "/home/{{ dock_user}}/.dockerdata"
    state: directory
    owner: "{{ dock_user }}"
    group: docker
    mode: '0755'

- name: Install docker configuration file from template
  become: yes
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  
