---
- name: Docker dependencies
  ansible.builtin.include_tasks:
    file: packages.yml
- name: Docker main
  ansible.builtin.include_tasks:
    file: docker.yml
- name: Docker desktop
  ansible.builtin.include_tasks:
    file: docker-desktop.yml
