---
- name: Add key
  ansible.builtin.command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C
- name: Add insync repo
  ansible.builtin.apt_repository:
    repo: "deb http://apt.insynchq.com/ubuntu artful non-free contrib"
    mode: 644

- name: Install insync
  ansible.builtin.apt:
    name:
      - insync
    state: present
    autoclean: true
    update_cache: true
