---
- name: Uncommon Software Packages
  ansible.builtin.include_tasks:
    file: packages.yml


- name: Spideroak Task
  ansible.builtin.include_tasks:
    file: spideroak.yml

- name: ProtonVPN
  ansible.builtin.include_tasks:
    file: protonvpn.yml
