---
- name: Uncommon Software Packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Spideroak Task
  ansible.builtin.include_tasks:
    file: spideroak.yml

- name: ProtonVPN
  ansible.builtin.include_tasks:
    file: protonvpn.yml

- name: Firefox developer
  ansible.builtin.include_tasks:
    file: firefox-developer.yml

- name: Force Quit
  ansible.builtin.include_tasks:
    file: force_quit.yml
