- name: Install utility packages common to all hosts
  apt:
    name:
      - keepass2
      - ansible-lint
      - gparted
      - xtightvncviewer
      - clementine
      - hexchat
    state: present
    autoclean: yes
