---
# - name: Gather package facts
#   package_facts:
#     manager: auto

# TODO find the latest download version https://spideroak.one/download
- name: "Install SpiderOak"
  ansible.builtin.apt:
    deb: https://spideroak-releases.s3.us-east-2.amazonaws.com/spideroakone_7.5.2_amd64.deb
#   when: '"spideroakone" not in ansible_facts.packages'
