---
# https://www.zotero.org/support/installation
# TODO: how to make sure this only runs once
- name: Zotero dependencies
  ansible.builtin.apt:
    name:
      - libreoffice-java-common

- name: Download Zotero application.
  ansible.builtin.get_url:
    dest: /tmp/Zotero-5.0.82_linux-x86_64.tar.bz2
    url: https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=5.0.82
    mode: "0644"

- name: Create zotero directory
  ansible.builtin.file:
    path: /opt/zotero
    state: directory
    mode: "0755"
  become: true

- name: Extract/Install zotero
  ansible.builtin.unarchive:
    dest: /opt/zotero
    src: /tmp/Zotero-5.0.82_linux-x86_64.tar.bz2
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    creates: /opt/zotero/Zotero_linux-x86_64
  become: true

- name: Create Desktop Shortcut
  ansible.builtin.command: /bin/bash /opt/zotero/Zotero_linux-x86_64/set_launcher_icon
  become: true
  register: uncommon_zotero_icon # <- Registers the command output.
  changed_when: uncommon_zotero_icon != 0 # <- Uses the return code to define when the task has changed.


- name: Add Zotero to Launcher
  ansible.builtin.file:
    src: /opt/zotero/Zotero_linux-x86_64/zotero.desktop
    dest: "/home/{{ ansible_facts['user_id'] }}/.local/share/applications/zotero.desktop"
    state: link
  when: uncommon_zotero_icon

# ln -s /opt/zotero/zotero.desktop ~/.local/share/applications/zotero.desktop

# Install the browser extension? You should be directed here after first launch
# This task based on https://gist.github.com/sanguis/8bf9ed0a78eca9ec258bc51aeb05873b
